const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STATE_KEY='futbolcontrol.beta.features.v3',COMBO_KEY='futbolcontrol.beta.combinations.v5';
function waitFor(s,cb,n=120){const el=$(s);if(el)return cb(el);if(n>0)setTimeout(()=>waitFor(s,cb,n-1),100);}
function load(k){try{return JSON.parse(localStorage.getItem(k)|| (k===COMBO_KEY?'[]':'{}'))}catch{return k===COMBO_KEY?[]:{}}}function save(k,v){localStorage.setItem(k,JSON.stringify(v));}
function dialog(){if($('#fc-v6-record-dialog'))return $('#fc-v6-record-dialog');const d=document.createElement('dialog');d.id='fc-v6-record-dialog';d.innerHTML='<form id="fc-v6-record-form"><div class="fc-v6-sheet-head"><div><small>FútbolControl beta</small><h2 id="fc-v6-record-title">Editar</h2></div><button type="button" data-close>×</button></div><div id="fc-v6-record-fields" class="fc-form"></div><div class="fc-actions"><button class="primary">Guardar cambios</button><button type="button" class="secondary" data-close>Cancelar</button></div></form>';document.body.appendChild(d);d.onclick=e=>{if(e.target.closest('[data-close]'))d.close();};return d;}
const SPECS={objectives:[['priority','Prioridad','text'],['status','Estado','text'],['reviewDate','Fecha de revisión','date'],['evidence','Evidencia','textarea']],positionTrials:[['position','Posición','text'],['system','Sistema','text'],['rating','Valoración 1–5','number'],['result','Conclusión','text'],['note','Observación','textarea']],evaluations:[['area','Área','text'],['criterion','Criterio','text'],['rating','Valoración 1–5','number'],['context','Contexto','text'],['date','Fecha','date'],['note','Observación','textarea']],planning:[['level','Nivel','text'],['problem','Problema','text'],['status','Estado','text'],['rating','Nivel actual 1–5','number'],['note','Notas','textarea']],diary:[['date','Fecha','date'],['objective','Objetivo','text'],['note','Notas','textarea']],rivals:[['name','Rival','text'],['system','Sistema','text'],['strengths','Fortalezas','textarea'],['weaknesses','Debilidades','textarea']],postMatches:[['phase','Fase','text'],['zone','Zona','text'],['scope','Alcance','text'],['cause','Causa probable','text'],['evidence','Evidencia','textarea']]};
function fields(record,spec){return spec.map(([k,l,t])=>t==='textarea'?`<label>${esc(l)}<textarea name="${esc(k)}">${esc(record[k]??'')}</textarea></label>`:`<label>${esc(l)}<input name="${esc(k)}" type="${t}" ${t==='number'&&/rating/.test(k)?'min="1" max="5" step="1"':''} value="${esc(record[k]??'')}"></label>`).join('');}
function openState(kind,id){const st=load(STATE_KEY),arr=Array.isArray(st[kind])?st[kind]:[],rec=arr.find(x=>x.id===id);if(!rec)return;const d=dialog(),spec=SPECS[kind]||Object.keys(rec).filter(k=>!['id','createdAt'].includes(k)&&['string','number'].includes(typeof rec[k])).slice(0,6).map(k=>[k,k,typeof rec[k]==='number'?'number':'text']);$('#fc-v6-record-title').textContent='Editar registro';$('#fc-v6-record-fields').innerHTML=fields(rec,spec);const f=$('#fc-v6-record-form');f.onsubmit=e=>{e.preventDefault();const latest=load(STATE_KEY),list=Array.isArray(latest[kind])?latest[kind]:[],i=list.findIndex(x=>x.id===id);if(i<0)return;const data=Object.fromEntries(new FormData(f)),next={...list[i]};for(const[k,v]of Object.entries(data))next[k]=/rating/.test(k)?Math.max(1,Math.min(5,Number(v)||1)):v;list[i]=next;latest[kind]=list;save(STATE_KEY,latest);d.close();location.reload();};d.showModal();}
function openCombo(id){const arr=load(COMBO_KEY),rec=arr.find(x=>x.id===id);if(!rec)return;const d=dialog(),spec=[['type','Tipo','text'],['system','Sistema','text'],['context','Contexto','text'],['apos','Posición A','text'],['bpos','Posición B','text'],['cpos','Posición C','text'],['sample','Muestra','text'],['date','Fecha','date'],['note','Observaciones','textarea']];$('#fc-v6-record-title').textContent='Editar combinación';$('#fc-v6-record-fields').innerHTML=fields(rec,spec);const f=$('#fc-v6-record-form');f.onsubmit=e=>{e.preventDefault();const list=load(COMBO_KEY),i=list.findIndex(x=>x.id===id);if(i<0)return;list[i]={...list[i],...Object.fromEntries(new FormData(f))};save(COMBO_KEY,list);d.close();location.reload();};d.showModal();}
function upgrade(){$$('[data-delete-kind]').forEach(del=>{const host=del.parentElement;if(!host||host.querySelector('[data-v6-edit-kind]'))return;const b=document.createElement('button');b.type='button';b.className='secondary compact';b.textContent='Editar';b.dataset.v6EditKind=del.dataset.deleteKind;b.dataset.v6EditId=del.dataset.id;host.insertBefore(b,del);});$$('[data-combo-remove-v5]').forEach(del=>{const card=del.closest('.fc-combo-card');if(!card||card.querySelector('[data-v6-edit-combo]'))return;const b=document.createElement('button');b.type='button';b.className='secondary compact';b.textContent='Editar';b.dataset.v6EditCombo=del.dataset.comboRemoveV5;del.parentElement?.insertBefore(b,del);});}
document.addEventListener('click',e=>{const a=e.target.closest('[data-v6-edit-kind]');if(a)return openState(a.dataset.v6EditKind,a.dataset.v6EditId);const c=e.target.closest('[data-v6-edit-combo]');if(c)return openCombo(c.dataset.v6EditCombo);});
waitFor('body',()=>{upgrade();new MutationObserver(upgrade).observe(document.body,{childList:true,subtree:true});});
