import { EJERCICIOS_VALIDADOS, toCampoBaseExercise } from '../js/ejercicios-validados.js';
import { REAL_EXERCISES, SLIDESHARE_EXERCISES } from '../js/real-exercises.js';
import { INITIAL_EXERCISES, PHASE2_V3_EXERCISES, EXERCISE_CATEGORIES } from '../js/training-domain.js';
import { TACTICAS_INTERACTIVAS } from '../js/tacticas-interactivas.js';

const STORAGE_KEY = 'futbolcontrol.beta.features.v3';
const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => [...r.querySelectorAll(s)];
const esc = (v = '') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid = () => crypto.randomUUID?.() || `fc-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const today = () => new Date().toISOString().slice(0, 10);
const normalize = (v = '') => String(v).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();

const PLAYERS = Object.freeze([
  {id:'p12',name:'Ramiro Casati',number:'1',foot:'Derecha',positions:['Portero'],rating:2},
  {id:'p04',name:'Eidan Asensio',number:'3',foot:'Derecha',positions:['Extremo','Delantero centro','Segundo delantero'],rating:2},
  {id:'p01',name:'Thiago Hernández',number:'4',foot:'Derecha',positions:['Central'],rating:4},
  {id:'p09',name:'Diego Andrés Anaya',number:'5',foot:'Derecha',positions:['Extremo'],rating:2},
  {id:'p05',name:'Nicolás Díaz-Saavedra',number:'6',foot:'Derecha',positions:[],rating:null},
  {id:'p08',name:'Alejandro Pedrós',number:'7',foot:'Izquierda',positions:['Central','Extremo','Delantero centro','Segundo delantero'],rating:2},
  {id:'p06',name:'Alejandro Suárez',number:'8',foot:'Izquierda',positions:['Central','Pivote/Mediocentro defensivo'],rating:3},
  {id:'p03',name:'Ignacio Poladura',number:'9',foot:'Derecha',positions:['Extremo','Delantero centro','Segundo delantero'],rating:3},
  {id:'p10',name:'Rodrigo Rodríguez',number:'10',foot:'Ambas',positions:['Central','Extremo'],rating:4},
  {id:'p11',name:'Aitor Navarro',number:'11',foot:'Derecha',positions:['Extremo'],rating:2},
  {id:'p02',name:'Javier Navarro',number:'12',foot:'Derecha',positions:['Mediapunta','Extremo'],rating:1},
  {id:'p07',name:'Pelayo Marrero',number:'15',foot:'Derecha',positions:['Central','Carrilero','Pivote/Mediocentro defensivo','Mediapunta','Delantero centro','Segundo delantero'],rating:4},
  {id:'2d3a94f6-2fbf-4e2a-818b-ec206bfc3aac',name:'Pablo Montesdeoca',number:'16',foot:'Derecha',positions:['Central','Pivote/Mediocentro defensivo','Mediapunta','Extremo','Segundo delantero'],rating:4},
  {id:'d7e874fb-ce40-4c19-879e-2be849f34663',name:'Marcel González',number:'18',foot:'Derecha',positions:['Extremo','Delantero centro'],rating:1},
  {id:'p13',name:'Pablo González',number:'20',foot:'Derecha',positions:['Central','Mediapunta','Extremo','Delantero centro','Segundo delantero'],rating:null},
]);

const MATCHES = Object.freeze([
  {id:'0a80bf9f-2bb8-4e0d-8b8d-7989446bbe01',date:'2026-09-09T18:00',type:'Amistoso',opponent:'Gran Canaria Alevín C',venue:'Mundial 82',status:'planned'},
  {id:'95db311d-e7d6-4592-bf45-61d9acad75d0',date:'2026-09-05T09:00',type:'Amistoso',opponent:'Vecindario Alevín C',venue:'Alfonso Silva',status:'finished',gf:1,ga:6},
]);

const AREAS = {
  'Técnica':['Control y primer toque','Pase corto','Pase medio/largo','Conducción','Regate 1v1','Protección de balón','Finalización','Golpeo','Juego aéreo','Pierna no dominante'],
  'Táctica con balón':['Salida de balón','Líneas de pase','Apoyos','Amplitud','Profundidad','Progresión','Juego entre líneas','Cambio de orientación','Fijar y soltar','Tercer hombre','Ocupación de área'],
  'Táctica sin balón':['Presión','Bloque y distancias','Protección del centro','Basculación','Cobertura','Permuta','Marcaje','Control de espalda','Temporización','Defensa del área','Vigilancias'],
  'Transiciones':['Reacción tras pérdida','Presión tras pérdida','Repliegue','Protección de transición','Contraataque','Primer pase tras robo','Segunda jugada'],
  'Percepción y decisión':['Escaneo','Orientación corporal','Toma de decisión','Velocidad de decisión','Identificar superioridad','Perfil para recibir','Comunicación'],
  'Comportamiento':['Participación sin balón','Concentración','Esfuerzo','Comunicación','Autonomía','Reacción al error','Cumplimiento de rol'],
  'Portero':['Posicionamiento','Blocaje','Desvío','Juego de pies','1 contra 1','Salidas','Juego aéreo','Comunicación'],
};

const POSITIONS = ['Portero','Central','Central derecho','Central izquierdo','Lateral derecho','Lateral izquierdo','Carrilero derecho','Carrilero izquierdo','Pivote/MCD','Mediocentro','Interior derecho','Interior izquierdo','Mediapunta','Extremo derecho','Extremo izquierdo','Delantero centro','Segundo delantero'];
const SYSTEMS_F7 = ['1-3-2-1','1-2-3-1','1-3-1-2','1-2-2-2','1-2-1-3','Libre / sin sistema'];
const CONTEXTS = ['Entrenamiento','Partido oficial','Amistoso','Torneo','Partidillo','Observación general'];
const STATUS_OPTIONS = ['Por iniciar','En trabajo','Mejorando','Consolidado','Revisar'];

const PROBLEMS = {
  'Salida ante presión':{phase:'Con balón',categories:['Táctica','Posesión','Técnico-táctico'],keywords:['salida de balón','superioridad','líneas de pase','portero jugador','apoyo','presión'],principle:'Crear superioridad y líneas de pase en primera fase'},
  'Pérdidas en salida':{phase:'Con balón',categories:['Técnico-táctico','Posesión','Táctica'],keywords:['control orientado','pase','salida de balón','apoyo','decisión','presión'],principle:'Asegurar primer control, apoyos y decisión bajo presión'},
  'Falta de amplitud':{phase:'Con balón',categories:['Táctica','Juego reducido'],keywords:['amplitud','banda','carril exterior','abrir','cambio de orientación'],principle:'Ocupar ancho útil para abrir pasillos interiores'},
  'Falta de profundidad':{phase:'Con balón',categories:['Táctica','Finalización','Juego reducido'],keywords:['profundidad','desmarque','ruptura','espalda','vertical','penetración'],principle:'Amenazar espalda y fijar profundidad'},
  'Pocas líneas de pase':{phase:'Con balón',categories:['Posesión','Técnico-táctico','Táctica'],keywords:['líneas de pase','apoyo','desmarque','triángulo','posesión','hombre libre'],principle:'Dar apoyos por delante, detrás y a los lados'},
  'Progresión lenta':{phase:'Con balón',categories:['Táctica','Posesión','Transición'],keywords:['progresión','vertical','tercer hombre','cambio de orientación','penetración'],principle:'Reconocer cuándo conservar y cuándo progresar'},
  'Embudo por dentro':{phase:'Con balón',categories:['Táctica','Juego reducido'],keywords:['amplitud','carril','banda','cambio de orientación','espacio'],principle:'Alternar dentro-fuera y mantener amplitud'},
  'Finalizamos poco':{phase:'Con balón',categories:['Finalización','Juego reducido','Técnico-táctico'],keywords:['finalización','tiro','remate','portería','ataque área','desmarque'],principle:'Generar y atacar situaciones claras de remate'},
  'Mala elección en último tercio':{phase:'Con balón',categories:['Finalización','Juego reducido','Táctico'],keywords:['decisión','finalización','superioridad','último pase','remate','3 contra 2'],principle:'Elegir pase, conducción o tiro según ventaja'},
  'Perdemos muchos 1v1 ofensivos':{phase:'Con balón',categories:['Tecnificación','Juego reducido'],keywords:['1 contra 1','1v1','regate','duelo','dribling','cambio de dirección'],principle:'Fijar al defensor y atacar su desequilibrio'},
  'Presión desordenada':{phase:'Sin balón',categories:['Táctica','Juego reducido','Transición'],keywords:['presión','cobertura','basculación','bloque','juntos','orientar'],principle:'Saltar con cobertura y orientar la salida rival'},
  'Bloque demasiado largo':{phase:'Sin balón',categories:['Táctica','Juego reducido'],keywords:['compacto','distancias','bloque','líneas','basculación','cobertura'],principle:'Reducir distancias entre líneas y alrededor del balón'},
  'Centro desprotegido':{phase:'Sin balón',categories:['Táctica','Juego reducido'],keywords:['centro','carril central','cobertura','basculación','proteger','interior'],principle:'Priorizar carril central antes que perseguir fuera'},
  'No basculamos juntos':{phase:'Sin balón',categories:['Táctica','Juego reducido'],keywords:['basculación','lado balón','bloque','cobertura','juntos'],principle:'Mover el bloque como una unidad hacia el balón'},
  'Coberturas tardías':{phase:'Sin balón',categories:['Táctica','Juego reducido'],keywords:['cobertura','permuta','ayuda','2 contra 1','equilibrio'],principle:'Dar una segunda defensa al compañero que salta'},
  'Perdemos marcas a espalda':{phase:'Sin balón',categories:['Táctica','Juego reducido'],keywords:['espalda','marcaje','escaneo','vigilancia','profundidad','defensa'],principle:'Escanear balón-rival-espacio y proteger profundidad'},
  'Defendemos demasiado atrás':{phase:'Sin balón',categories:['Táctica','Juego reducido'],keywords:['bloque','avanzar','defender hacia delante','presión','distancias'],principle:'Defender hacia delante sin hundirse sobre portería'},
  'Malos duelos defensivos':{phase:'Sin balón',categories:['Juego reducido','Técnico-táctico','Preparación física integrada'],keywords:['1 contra 1','1v1','duelo','temporizar','orientar','entrada'],principle:'Temporizar, orientar y elegir momento de robo'},
  'Reacción lenta tras pérdida':{phase:'Transición defensiva',categories:['Transición','Juego reducido','Táctica'],keywords:['tras pérdida','reacción','presión inmediata','transición','recuperar','3 segundos'],principle:'Primeros segundos activos tras perder'},
  'Repliegue lento':{phase:'Transición defensiva',categories:['Transición','Juego reducido'],keywords:['repliegue','transición defensiva','volver','proteger centro','equilibrio'],principle:'Correr primero hacia zona de protección y reorganizar'},
  'Nos cogen en contraataque':{phase:'Transición defensiva',categories:['Transición','Táctica'],keywords:['transición defensiva','equilibrio','vigilancia','contraataque','proteger'],principle:'Mantener equilibrio preventivo mientras atacamos'},
  'Contraataque lento':{phase:'Transición ofensiva',categories:['Transición','Juego reducido'],keywords:['contraataque','tras robo','vertical','profundidad','transición ofensiva'],principle:'Primer pase útil y amenaza inmediata de profundidad'},
  'No aprovechamos superioridades':{phase:'Transición ofensiva',categories:['Transición','Juego reducido','Técnico-táctico'],keywords:['superioridad','2 contra 1','3 contra 2','fijar','soltar','hombre libre'],principle:'Fijar rival y liberar compañero'},
  'Mala segunda jugada':{phase:'Transiciones',categories:['Transición','Juego reducido'],keywords:['segunda jugada','rechace','balón dividido','apoyo','cobertura'],principle:'Preparar apoyos alrededor del balón directo'},
  'Saque de banda poco útil':{phase:'ABP',categories:['Táctica','Técnico-táctico'],keywords:['saque de banda','banda','apoyo','desmarque'],principle:'Crear dos líneas de pase y continuidad tras saque'},
  'Córner ofensivo':{phase:'ABP',categories:['Táctica','Finalización'],keywords:['córner','corner','remate','segundo palo','bloqueo'],principle:'Ocupar zonas de remate y proteger rechace'},
  'Córner defensivo':{phase:'ABP',categories:['Táctica'],keywords:['córner','corner','marcaje','rechace','defensa área'],principle:'Proteger zonas prioritarias y salida tras despeje'},
  'Portero: juego de pies':{phase:'Portero',categories:['Porteros','Técnico-táctico'],keywords:['portero','juego de pies','salida','pase','apoyo'],principle:'Integrar al portero como apoyo seguro'},
  'Portero: blocaje/seguridad':{phase:'Portero',categories:['Porteros'],keywords:['portero','blocaje','agarre','desvío','tiro'],principle:'Asegurar posición, manos y segunda acción'},
  'Baja participación sin balón':{phase:'Comportamiento',categories:['Juego reducido','Posesión','Técnico-táctico'],keywords:['desmarque','apoyo','movilidad','participación','línea de pase','reacción'],principle:'Participar antes y después de tocar balón'},
  'Falta de comunicación':{phase:'Comportamiento',categories:['Táctica','Juego reducido'],keywords:['comunicación','organizar','cobertura','ayuda','información'],principle:'Dar información útil antes, durante y después de la acción'},
};

const CAUSES = ['Técnica insuficiente','Mala orientación corporal','Falta de escaneo/información','Distancias incorrectas','Mala ocupación de espacios','Timing incorrecto','Falta de apoyos','Decisión tardía','Descoordinación colectiva','Reacción tras pérdida insuficiente','Falta de intensidad','No comprende el rol','Rival genera superioridad','Hipótesis por confirmar'];
const ZONES = ['Todo el campo','Inicio / salida','Carril central','Banda derecha','Banda izquierda','Zona intermedia','Último tercio','Área propia','Área rival'];
const SCOPES = ['Colectivo','Línea defensiva','Centrocampo','Ataque','Portero','Jugador concreto'];

const defaultState = () => ({
  identity:{teamName:'Unión Viera Alevín D',primary:'#0b5b49',secondary:'#17211d',accent:'#c3a654',crest:''},
  objectives:[], positionTrials:[], evaluations:[], postMatches:[], planning:[], diary:[], rivals:[], sessionDraft:[],
});
let state = loadState();
let lastRecommendations = [];
let lastTacticRecommendations = [];

function loadState(){
  try { return {...defaultState(), ...JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}')}; } catch { return defaultState(); }
}
function saveState(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); renderDashboard(); }
function options(items, selected = ''){ return items.map(x => `<option value="${esc(x)}" ${x===selected?'selected':''}>${esc(x)}</option>`).join(''); }
function playerOptions(selected=''){ return PLAYERS.map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>#${esc(p.number)} · ${esc(p.name)}</option>`).join(''); }
function matchOptions(){ return MATCHES.map(m=>`<option value="${m.id}">${esc(m.opponent)} · ${m.date.slice(0,10).split('-').reverse().join('/')} · ${m.type}</option>`).join(''); }
function formatDate(v){ if(!v)return '—'; const [y,m,d]=v.slice(0,10).split('-'); return `${d}/${m}/${y}`; }
function playerName(id){ return PLAYERS.find(p=>p.id===id)?.name || 'Jugador'; }
function playerById(id){ return PLAYERS.find(p=>p.id===id); }

function createSection(id,title,subtitle=''){
  const main=$('#app'); const section=document.createElement('section');
  section.id=id; section.className='view';
  section.innerHTML=`<div class="section-head"><div><p class="eyebrow">FútbolControl Beta</p><h2>${esc(title)}</h2>${subtitle?`<p class="meta">${esc(subtitle)}</p>`:''}</div><span class="fc-beta-badge">LAB AISLADO</span></div><div class="fc-root"></div>`;
  main.insertBefore(section, main.firstElementChild); return section.querySelector('.fc-root');
}
function addNav(id,label){
  const nav=$('.bottom-nav'); const b=document.createElement('button'); b.type='button'; b.dataset.view=id; b.className='fc-nav-new'; b.textContent=label; nav.insertBefore(b, nav.firstChild);
  b.addEventListener('click',()=>{ $$('.view').forEach(v=>v.classList.toggle('active',v.id===id)); $$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x===b)); $('#app')?.focus(); });
}
function bindSubnav(root){
  root.addEventListener('click',e=>{ const b=e.target.closest('[data-fc-pane]'); if(!b)return; const pane=b.dataset.fcPane; $$('.fc-subnav button',root).forEach(x=>x.classList.toggle('active',x===b)); $$('.fc-pane',root).forEach(x=>x.classList.toggle('active',x.dataset.pane===pane)); });
}

function setupBrand(){
  document.title='FútbolControl · Laboratorio';
  const brand=$('.topbar-brand'); if(brand){ const img=$('img',brand); if(img){img.src='lab/futbolcontrol-logo.svg';img.alt='FútbolControl';} const h=$('h1',brand);if(h)h.textContent='FútbolControl'; const e=$('.eyebrow',brand);if(e)e.textContent='Gestión integral de fútbol'; }
  const net=$('#network-label'); if(net){net.textContent='LAB · Solo local';net.title='No hay conexión con Supabase real.';}
  const role=$('#role-label'); if(role)role.textContent='Entrenador · LAB';
  $('#logout')?.remove();
  document.body.classList.remove('auth-locked'); try{ if($('#auth-dialog')?.open) $('#auth-dialog').close(); }catch{}
  if(!$('.fc-lab-ribbon')) $('.topbar')?.insertAdjacentHTML('afterend','<div class="fc-lab-ribbon">FÚTBOLCONTROL BETA · copia completa aislada · guardado solo en este navegador</div>');
  applyIdentity();
}
function applyIdentity(){
  const i=state.identity; document.documentElement.style.setProperty('--fc-primary',i.primary); document.documentElement.style.setProperty('--fc-secondary',i.secondary); document.documentElement.style.setProperty('--fc-accent',i.accent);
  const top=$('.topbar'); if(top) top.style.background=i.primary;
  $$('.primary').forEach(b=>{b.style.background=i.primary;b.style.borderColor=i.primary;});
  const img=$('.topbar-brand img'); if(img) img.src=i.crest || 'lab/futbolcontrol-logo.svg';
}

function setupDashboard(){
  const root=createSection('fc-inicio','Inicio','Resumen deportivo y accesos rápidos'); addNav('fc-inicio','Inicio');
  root.innerHTML='<div id="fc-dashboard"></div>'; renderDashboard();
}
function renderDashboard(){
  const root=$('#fc-dashboard'); if(!root)return;
  const activeObj=state.objectives.filter(x=>!['Consolidado'].includes(x.status));
  const next=MATCHES.find(m=>m.status==='planned'); const last=MATCHES.find(m=>m.status==='finished'); const lastPost=state.postMatches.at(-1);
  root.innerHTML=`<div class="fc-grid">
    <article class="fc-card"><span class="fc-muted">Plantilla</span><div class="fc-kpi">${PLAYERS.length}</div><p>${PLAYERS.filter(p=>p.rating!==null).length} con valoración reciente · escala 1–5</p></article>
    <article class="fc-card"><span class="fc-muted">Próximo partido</span><h3>${esc(next.opponent)}</h3><p>${formatDate(next.date)} · ${esc(next.date.slice(11,16))} · ${esc(next.venue)}</p><span class="fc-tag">${esc(next.type)}</span></article>
    <article class="fc-card"><span class="fc-muted">Último partido</span><h3>${esc(last.opponent)}</h3><div class="fc-match-score">${last.gf}-${last.ga}</div><p>${formatDate(last.date)} · ${esc(last.type)}</p></article>
    <article class="fc-card"><span class="fc-muted">Objetivos individuales activos</span><div class="fc-kpi">${activeObj.length}</div><p>${new Set(activeObj.map(x=>x.playerId)).size} jugadores con seguimiento</p></article>
  </div>
  <div class="fc-two" style="margin-top:14px"><article class="panel"><h3>Prioridades actuales</h3>${lastPost?lastPost.problems.map((p,i)=>`<div class="fc-row"><div><strong>${i+1}. ${esc(p)}</strong><div class="fc-muted">${esc(PROBLEMS[p]?.principle||'')}</div></div></div>`).join(''):'<div class="fc-empty">Todavía no hay un postpartido guardado. Al registrar uno aparecerán aquí sus 1–3 prioridades.</div>'}</article><article class="panel"><h3>Jugadores a revisar</h3>${activeObj.length?activeObj.slice(0,5).map(o=>`<div class="fc-row"><div><strong>${esc(playerName(o.playerId))}</strong><div class="fc-muted">${esc(o.principle)} · ${esc(o.status)}</div></div><span class="fc-tag ${o.priority==='Alta'?'warn':''}">${esc(o.priority)}</span></div>`).join(''):'<div class="fc-empty">Añade objetivos en Desarrollo individual.</div>'}</article></div>`;
}

function setupDevelopment(){
  const root=createSection('fc-desarrollo','Desarrollo individual','Objetivos, pruebas de posición y evaluaciones 1–5'); addNav('fc-desarrollo','Desarrollo');
  root.innerHTML=`<div class="fc-subnav"><button type="button" class="active" data-fc-pane="obj">Objetivos</button><button type="button" data-fc-pane="pos">Pruebas de posición</button><button type="button" data-fc-pane="eval">Evaluaciones 1–5</button></div>
    <div class="fc-pane active" data-pane="obj"><div class="fc-two"><article class="panel"><h3>Nuevo objetivo individual</h3><form id="fc-objective-form" class="fc-form"><label>Jugador<select name="playerId">${playerOptions()}</select></label><div class="fc-two"><label>Área<select name="area">${options(Object.keys(AREAS))}</select></label><label>Principio / contenido<select name="principle"></select></label></div><div class="fc-three"><label>Prioridad<select name="priority">${options(['Alta','Media','Baja'])}</select></label><label>Estado<select name="status">${options(STATUS_OPTIONS)}</select></label><label>Contexto<select name="context">${options(CONTEXTS)}</select></label></div><label>Fecha de revisión<input name="reviewDate" type="date" value="${today()}"></label><label>Evidencia / qué observar<textarea name="evidence" placeholder="Describe una conducta observable, no una etiqueta del jugador."></textarea></label><button class="primary">Guardar objetivo</button></form></article><article class="panel"><h3>Objetivos guardados</h3><div id="fc-objective-list"></div></article></div></div>
    <div class="fc-pane" data-pane="pos"><div class="fc-two"><article class="panel"><h3>Nueva prueba de posición</h3><form id="fc-position-form" class="fc-form"><label>Jugador<select name="playerId">${playerOptions()}</select></label><div class="fc-two"><label>Posición<select name="position">${options(POSITIONS)}</select></label><label>Sistema<select name="system">${options(SYSTEMS_F7)}</select></label></div><div class="fc-three"><label>Lado<select name="side">${options(['Centro','Derecha','Izquierda','Indiferente'])}</select></label><label>Contexto<select name="context">${options(CONTEXTS)}</select></label><label>Valoración<select name="rating">${options(['1','2','3','4','5'],'3')}</select></label></div><label>Rol concreto<select name="role">${options(['Referencia','Organizador','Equilibrio/cobertura','Profundidad','Amplitud','Apoyo interior','Presión','Finalizador','Salida de balón','Por descubrir'])}</select></label><label>Conclusión provisional<select name="result">${options(['Seguir probando','Buena adaptación','Adaptación irregular','Dudas','No encajó en este contexto'])}</select></label><label>Fecha<input name="date" type="date" value="${today()}"></label><label>Observación<textarea name="note" placeholder="Qué hizo en esa posición y en qué contexto."></textarea></label><button class="primary">Guardar prueba</button></form></article><article class="panel"><h3>Historial de posiciones</h3><div id="fc-position-list"></div></article></div></div>
    <div class="fc-pane" data-pane="eval"><div class="fc-two"><article class="panel"><h3>Nueva evaluación</h3><form id="fc-eval-form" class="fc-form"><label>Jugador<select name="playerId">${playerOptions()}</select></label><div class="fc-two"><label>Dimensión<select name="area">${options(Object.keys(AREAS))}</select></label><label>Criterio<select name="criterion"></select></label></div><div class="fc-three"><label>Puntuación<select name="rating">${options(['1','2','3','4','5'],'3')}</select></label><label>Contexto<select name="context">${options(CONTEXTS)}</select></label><label>Fecha<input name="date" type="date" value="${today()}"></label></div><label>Observación<textarea name="note" placeholder="Evidencia que justifica la valoración."></textarea></label><button class="primary">Guardar evaluación</button></form></article><article class="panel"><h3>Evolución registrada</h3><div id="fc-eval-list"></div></article></div></div>`;
  bindSubnav(root); wireDevelopment(); renderDevelopment();
}
function fillAreaPrinciples(form){ const area=form.elements.area.value; form.elements.principle ? form.elements.principle.innerHTML=options(AREAS[area]||[]) : form.elements.criterion.innerHTML=options(AREAS[area]||[]); }
function wireDevelopment(){
  const of=$('#fc-objective-form'); fillAreaPrinciples(of); of.elements.area.addEventListener('change',()=>fillAreaPrinciples(of)); of.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(of);state.objectives.push({id:uid(),playerId:f.get('playerId'),area:f.get('area'),principle:f.get('principle'),priority:f.get('priority'),status:f.get('status'),context:f.get('context'),reviewDate:f.get('reviewDate'),evidence:f.get('evidence').trim(),createdAt:Date.now()});saveState();renderDevelopment();});
  const pf=$('#fc-position-form'); pf.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(pf);state.positionTrials.push({id:uid(),playerId:f.get('playerId'),position:f.get('position'),system:f.get('system'),side:f.get('side'),context:f.get('context'),rating:Number(f.get('rating')),role:f.get('role'),result:f.get('result'),date:f.get('date'),note:f.get('note').trim()});saveState();renderDevelopment();});
  const ef=$('#fc-eval-form'); fillAreaPrinciples(ef); ef.elements.area.addEventListener('change',()=>fillAreaPrinciples(ef)); ef.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(ef);state.evaluations.push({id:uid(),playerId:f.get('playerId'),area:f.get('area'),criterion:f.get('criterion'),rating:Number(f.get('rating')),context:f.get('context'),date:f.get('date'),note:f.get('note').trim()});saveState();renderDevelopment();});
  $('#fc-desarrollo').addEventListener('click',e=>{const b=e.target.closest('[data-delete-kind]');if(!b)return;state[b.dataset.deleteKind]=state[b.dataset.deleteKind].filter(x=>x.id!==b.dataset.id);saveState();renderDevelopment();});
}
function renderDevelopment(){
  const ol=$('#fc-objective-list'); if(ol) ol.innerHTML=state.objectives.length?state.objectives.slice().reverse().map(o=>`<div class="fc-row"><div class="fc-row-main"><strong>${esc(playerName(o.playerId))}</strong><div>${esc(o.principle)}</div><div class="fc-muted">${esc(o.area)} · ${esc(o.context)} · revisar ${formatDate(o.reviewDate)}</div>${o.evidence?`<div class="fc-small">${esc(o.evidence)}</div>`:''}</div><div class="fc-row-actions"><span class="fc-tag ${o.priority==='Alta'?'warn':''}">${esc(o.status)}</span><button type="button" class="danger" data-delete-kind="objectives" data-id="${o.id}">×</button></div></div>`).join(''):'<div class="fc-empty">Sin objetivos todavía.</div>';
  const pl=$('#fc-position-list'); if(pl) pl.innerHTML=state.positionTrials.length?state.positionTrials.slice().reverse().map(x=>`<div class="fc-row"><div><strong>${esc(playerName(x.playerId))} · ${esc(x.position)}</strong><div class="fc-muted">${esc(x.system)} · ${esc(x.side)} · ${esc(x.context)} · ${formatDate(x.date)}</div><div>${esc(x.role)} · <strong>${x.rating}/5</strong> · ${esc(x.result)}</div>${x.note?`<div class="fc-small">${esc(x.note)}</div>`:''}</div><button type="button" class="danger" data-delete-kind="positionTrials" data-id="${x.id}">×</button></div>`).join(''):'<div class="fc-empty">Sin posiciones probadas.</div>';
  const el=$('#fc-eval-list'); if(el) el.innerHTML=state.evaluations.length?state.evaluations.slice().reverse().map(x=>`<div class="fc-row"><div><strong>${esc(playerName(x.playerId))} · ${esc(x.criterion)}</strong><div class="fc-muted">${esc(x.area)} · ${esc(x.context)} · ${formatDate(x.date)}</div>${x.note?`<div class="fc-small">${esc(x.note)}</div>`:''}</div><span class="fc-rating">${x.rating}/5</span><button type="button" class="danger" data-delete-kind="evaluations" data-id="${x.id}">×</button></div>`).join(''):'<div class="fc-empty">Sin evaluaciones todavía.</div>';
}

function buildExerciseCatalog(){
  const rich=EJERCICIOS_VALIDADOS.map(v=>{const base=toCampoBaseExercise(v);return {...base,_rich:v,_source:'Ficha completa',_validated:v.estado==='validado'};});
  const generic=[...INITIAL_EXERCISES,...PHASE2_V3_EXERCISES,...REAL_EXERCISES,...SLIDESHARE_EXERCISES].map(x=>({...x,_source:'Biblioteca CampoBase',_validated:true}));
  const map=new Map(); [...generic,...rich].forEach(x=>{if(x?.id)map.set(x.id,x);}); return [...map.values()];
}
const EXERCISES=buildExerciseCatalog();
function exerciseText(ex){ const r=ex._rich; return normalize([ex.name,ex.category,ex.description,ex.variants,ex.material,r?.vista_rapida?.que_se_trabaja?.join(' '),r?.vista_rapida?.explicacion_breve,r?.detalle?.objetivos?.join(' '),r?.detalle?.que_buscamos?.join(' '),r?.detalle?.que_observar?.join(' '),r?.detalle?.correcciones?.join(' ')].filter(Boolean).join(' ')); }
function parsePlayers(ex){ const rich=ex._rich?.vista_rapida?.jugadores?.total; if(Number.isFinite(rich)) return [rich,rich]; const nums=String(ex.players||'').match(/\d+/g)?.map(Number)||[]; if(!nums.length)return null; return nums.length===1?[nums[0],nums[0]]:[Math.min(...nums),Math.max(...nums)]; }
function parseDuration(ex){ if(Number.isFinite(Number(ex.duration)))return Number(ex.duration); const s=ex._rich?.vista_rapida?.tiempo_estimado_15||''; const nums=String(s).match(/\d+/g)?.map(Number)||[]; return nums.length?Math.round(nums.reduce((a,b)=>a+b,0)/nums.length):null; }
function recommendationScore(ex, problems, filters){
  const text=exerciseText(ex); let score=0; const reasons=[]; const matched=[];
  problems.forEach(name=>{const p=PROBLEMS[name]; if(!p)return; let local=0; p.keywords.forEach(k=>{if(text.includes(normalize(k)))local+=3;}); if(p.categories.includes(ex.category))local+=7; if(local){score+=Math.min(local,22);matched.push(name);}});
  if(matched.length)reasons.push(`Ataca ${matched.slice(0,2).join(' + ')}`);
  const range=parsePlayers(ex); if(range&&filters.players){const n=filters.players;if(n>=range[0]&&n<=range[1]){score+=10;reasons.push(`Encaja con ${n} jugadores`);}else if(Math.abs(n-range[0])<=2||Math.abs(n-range[1])<=2){score+=4;reasons.push('Adaptable al número de jugadores');}}
  const dur=parseDuration(ex); if(dur&&filters.duration){const diff=Math.abs(dur-filters.duration);if(diff<=3){score+=7;reasons.push(`Duración cercana a ${filters.duration} min`);}else if(diff<=7)score+=3;}
  if(filters.difficulty==='Cualquiera'||!ex.difficulty)score+=2; else if(normalize(ex.difficulty)===normalize(filters.difficulty)){score+=5;reasons.push(`Dificultad ${filters.difficulty}`);}
  const material=normalize(ex.material||ex._rich?.vista_rapida?.material||''); if(filters.material==='Poco material'&&/(conos|balon|petos)/.test(material)&&!/escalera|valla|pica|silueta/.test(material)){score+=4;reasons.push('Montaje sencillo');} if(filters.material==='Con porterías'&&/porteria/.test(material)){score+=4;reasons.push('Usa porterías');} if(filters.material==='Sin porterías'&&!/porteria/.test(material))score+=3;
  if(ex._validated)score+=5; return {ex,score:Math.min(100,Math.round(score*1.45)),reasons,matched};
}
function tacticText(t){return normalize([t.nombre,t.principio,t.organizacion,...(t.bloques||[]).flatMap(b=>[b.titulo,b.objetivo,b.idea_clave,...(b.decisiones||[]),...(b.observar||[])])].filter(Boolean).join(' '));}
function recommendTactics(problems){return TACTICAS_INTERACTIVAS.map(t=>{const text=tacticText(t);let score=0;const matches=[];problems.forEach(name=>{const p=PROBLEMS[name];let local=0;p?.keywords.forEach(k=>{if(text.includes(normalize(k)))local+=3;});if(local){score+=local;matches.push(name);}});const blocks=(t.bloques||[]).map(b=>{const bt=normalize([b.titulo,b.objetivo,b.idea_clave,...(b.decisiones||[])].join(' '));let s=0;problems.forEach(name=>PROBLEMS[name]?.keywords.forEach(k=>{if(bt.includes(normalize(k)))s++;}));return {b,s};}).sort((a,b)=>b.s-a.s);return {t,score,matches,block:blocks[0]?.b};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3);}

function setupPostmatch(){
  const root=createSection('fc-postpartido','Postpartido → entrenamiento','Analiza el problema antes de recomendar ejercicios'); addNav('fc-postpartido','Postpartido');
  root.innerHTML=`<div class="fc-two"><article class="panel"><h3>1. Qué ocurrió</h3><form id="fc-post-form" class="fc-form"><label>Partido<select name="matchId">${matchOptions()}</select></label><div class="fc-three"><label>Fase<select name="phase">${options(['Con balón','Sin balón','Transición defensiva','Transición ofensiva','ABP','Portero','Comportamiento'])}</select></label><label>Zona<select name="zone">${options(ZONES)}</select></label><label>Alcance<select name="scope">${options(SCOPES)}</select></label></div><label>Problema 1<select name="p1">${options(Object.keys(PROBLEMS))}</select></label><label>Problema 2<select name="p2"><option value="">— Sin segundo problema —</option>${options(Object.keys(PROBLEMS))}</select></label><label>Problema 3<select name="p3"><option value="">— Sin tercer problema —</option>${options(Object.keys(PROBLEMS))}</select></label><label>Causa probable<select name="cause">${options(CAUSES)}</select></label><label>Evidencia<textarea name="evidence" placeholder="Qué viste exactamente. Ej.: tras pérdida, 3 jugadores se quedan parados y el rival progresa por dentro."></textarea></label><div class="fc-divider"></div><h4>Filtros para recomendar tareas</h4><div class="fc-two"><label>Jugadores disponibles<select name="players">${options(Array.from({length:20},(_,i)=>String(i+5)),String(14))}</select></label><label>Tiempo por tarea<select name="duration">${options(['8','10','12','15','18','20','25'],'15')}</select></label></div><div class="fc-two"><label>Dificultad<select name="difficulty">${options(['Cualquiera','Baja','Media','Alta'],'Cualquiera')}</select></label><label>Material<select name="material">${options(['Cualquiera','Poco material','Con porterías','Sin porterías'],'Cualquiera')}</select></label></div><button class="primary">Analizar y recomendar</button></form></article><article class="panel"><h3>2. Principio a corregir</h3><div id="fc-problem-analysis" class="fc-empty">Selecciona el problema y pulsa «Analizar y recomendar».</div><div class="fc-divider"></div><h3>3. Borrador de sesión</h3><div id="fc-session-draft"></div></article></div><article class="panel" style="margin-top:14px"><h3>4. Ejercicios CampoBase analizados</h3><p class="fc-muted">La puntuación combina contenido real de la ficha, problema, categoría, jugadores, duración, dificultad y material.</p><div id="fc-recommendations" class="fc-empty">Sin análisis todavía.</div></article><article class="panel" style="margin-top:14px"><h3>5. Tácticas y bloques relacionados</h3><div id="fc-tactic-recommendations" class="fc-empty">Sin análisis todavía.</div></article>`;
  wirePostmatch(); renderSessionDraft();
}
function wirePostmatch(){
  const form=$('#fc-post-form'); form.elements.phase.addEventListener('change',()=>{const phase=form.elements.phase.value;const names=Object.keys(PROBLEMS).filter(k=>PROBLEMS[k].phase===phase||phase==='ABP'&&PROBLEMS[k].phase==='ABP');['p1','p2','p3'].forEach((n,i)=>{const current=form.elements[n].value;form.elements[n].innerHTML=(i?'<option value="">— Ninguno —</option>':'')+options(names,current);});});
  form.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(form);const problems=[f.get('p1'),f.get('p2'),f.get('p3')].filter(Boolean);const filters={players:Number(f.get('players')),duration:Number(f.get('duration')),difficulty:f.get('difficulty'),material:f.get('material')};const scored=EXERCISES.map(ex=>recommendationScore(ex,problems,filters)).filter(x=>x.score>10).sort((a,b)=>b.score-a.score);lastRecommendations=scored.slice(0,7);lastTacticRecommendations=recommendTactics(problems);state.postMatches.push({id:uid(),matchId:f.get('matchId'),phase:f.get('phase'),zone:f.get('zone'),scope:f.get('scope'),problems,cause:f.get('cause'),evidence:f.get('evidence').trim(),filters,createdAt:Date.now()});saveState();renderProblemAnalysis(problems,f.get('cause'));renderRecommendations();renderTacticRecommendations();});
  $('#fc-postpartido').addEventListener('click',e=>{const b=e.target.closest('[data-add-exercise]');if(b){const item=lastRecommendations.find(x=>x.ex.id===b.dataset.addExercise);if(item){state.sessionDraft.push({id:uid(),kind:'E',name:item.ex.name,minutes:parseDuration(item.ex)||15,source:'exercise',sourceId:item.ex.id});saveState();renderSessionDraft();}}const t=e.target.closest('[data-add-tactic]');if(t){const item=lastTacticRecommendations[Number(t.dataset.addTactic)];if(item){state.sessionDraft.push({id:uid(),kind:'T',name:`${item.t.nombre} — ${item.block?.titulo||'Bloque recomendado'}`,minutes:15,source:'tactic',sourceId:item.t.id});saveState();renderSessionDraft();}}const del=e.target.closest('[data-draft-delete]');if(del){state.sessionDraft=state.sessionDraft.filter(x=>x.id!==del.dataset.draftDelete);saveState();renderSessionDraft();}});
  $('#fc-postpartido').addEventListener('change',e=>{const row=e.target.closest('[data-draft-id]');if(!row)return;const item=state.sessionDraft.find(x=>x.id===row.dataset.draftId);if(!item)return;if(e.target.name==='kind')item.kind=e.target.value;if(e.target.name==='minutes')item.minutes=Math.max(1,Math.min(60,Number(e.target.value)||1));saveState();renderSessionDraft();});
}
function renderProblemAnalysis(problems,cause){const el=$('#fc-problem-analysis');el.className='';el.innerHTML=problems.map((p,i)=>`<div class="fc-card"><div class="fc-title-line"><h4>${i+1}. ${esc(p)}</h4><span class="fc-tag">${esc(PROBLEMS[p].phase)}</span></div><p><strong>Principio:</strong> ${esc(PROBLEMS[p].principle)}</p><p class="fc-muted">Causa seleccionada: ${esc(cause)}. La app la trata como hipótesis, no como hecho.</p></div>`).join('');}
function renderRecommendations(){const root=$('#fc-recommendations');if(!lastRecommendations.length){root.className='fc-empty';root.textContent='No encontré tareas con suficiente coincidencia. Prueba menos filtros o revisa la causa.';return;}root.className='fc-reco';root.innerHTML=lastRecommendations.map(({ex,score,reasons})=>`<article class="fc-reco-card"><div class="fc-reco-head"><div><h4>${esc(ex.name)}</h4><div><span class="fc-tag">${esc(ex.category||'Sin categoría')}</span><span class="fc-tag neutral">${esc(ex._source)}</span></div></div><span class="fc-score">${score}/100</span></div><ul class="fc-reasons">${reasons.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><div class="fc-observe"><strong>Qué observar:</strong> ${esc(ex._rich?.detalle?.que_observar?.slice(0,2).join(' · ')||ex.description||'Revisa la ejecución y si aparece el principio buscado.')}</div><div class="fc-actions"><button type="button" class="primary" data-add-exercise="${esc(ex.id)}">Añadir al borrador</button></div></article>`).join('');}
function renderTacticRecommendations(){const root=$('#fc-tactic-recommendations');if(!lastTacticRecommendations.length){root.className='fc-empty';root.textContent='No hay bloque táctico con coincidencia suficiente.';return;}root.className='fc-reco';root.innerHTML=lastTacticRecommendations.map((x,i)=>`<article class="fc-reco-card"><div class="fc-title-line"><h4>${esc(x.t.nombre)}</h4><span class="fc-tag">${esc(x.t.formacion||'F7')}</span></div><p><strong>Bloque:</strong> ${esc(x.block?.titulo||'Revisar guía completa')}</p><p>${esc(x.block?.objetivo||x.t.principio||'')}</p><div class="fc-actions"><button type="button" class="primary" data-add-tactic="${i}">Añadir bloque táctico</button></div></article>`).join('');}
function renderSessionDraft(){const root=$('#fc-session-draft');if(!root)return;const total=state.sessionDraft.reduce((s,x)=>s+Number(x.minutes||0),0);root.innerHTML=`<div class="fc-status-line"><strong>Total: ${total} min</strong><span class="fc-tag ${total===60?'good':total>60?'bad':'warn'}">${total===60?'60 min exactos':total<60?`faltan ${60-total}`:`sobran ${total-60}`}</span></div><div class="fc-session-plan" style="margin-top:10px">${state.sessionDraft.length?state.sessionDraft.map(x=>`<div class="fc-session-block" data-draft-id="${x.id}"><input class="fc-session-min" name="minutes" type="number" min="1" max="60" value="${x.minutes}" aria-label="Minutos"><div><select name="kind"><option ${x.kind==='C'?'selected':''}>C</option><option ${x.kind==='E'?'selected':''}>E</option><option ${x.kind==='T'?'selected':''}>T</option><option ${x.kind==='P'?'selected':''}>P</option></select><strong style="margin-left:7px">${esc(x.name)}</strong></div><button type="button" class="danger" data-draft-delete="${x.id}">×</button></div>`).join(''):'<div class="fc-empty">Añade ejercicios o bloques tácticos desde las recomendaciones.</div>'}</div>`;}

function setupPlanning(){
  const root=createSection('fc-planificacion','Planificación','Temporada, mes, semana y diario de entrenamiento'); addNav('fc-planificacion','Planificación');
  root.innerHTML=`<div class="fc-subnav"><button type="button" class="active" data-fc-pane="plan">Objetivos</button><button type="button" data-fc-pane="diary">Diario</button><button type="button" data-fc-pane="map">Mapa de necesidades</button></div><div class="fc-pane active" data-pane="plan"><div class="fc-two"><article class="panel"><h3>Nuevo objetivo de planificación</h3><form id="fc-plan-form" class="fc-form"><div class="fc-two"><label>Nivel<select name="level">${options(['Temporada','Mes','Semana'])}</select></label><label>Prioridad<select name="priority">${options(['1 · Principal','2 · Secundaria','3 · Complementaria'])}</select></label></div><label>Problema / necesidad<select name="problem">${options(Object.keys(PROBLEMS))}</select></label><div class="fc-two"><label>Estado<select name="status">${options(['Por trabajar','Iniciado','En progreso','Consolidado','Revisar'])}</select></label><label>Nivel actual<select name="rating">${options(['1','2','3','4','5'],'2')}</select></label></div><div class="fc-two"><label>Desde<input name="start" type="date" value="${today()}"></label><label>Hasta<input name="end" type="date"></label></div><label>Notas<textarea name="note" placeholder="Qué queremos que el equipo sea capaz de hacer."></textarea></label><button class="primary">Guardar objetivo</button></form></article><article class="panel"><h3>Plan actual</h3><div id="fc-plan-list"></div></article></div></div><div class="fc-pane" data-pane="diary"><div class="fc-two"><article class="panel"><h3>Diario postentrenamiento</h3><form id="fc-diary-form" class="fc-form"><label>Fecha<input name="date" type="date" value="${today()}"></label><label>Objetivo trabajado<select name="problem">${options(Object.keys(PROBLEMS))}</select></label><div class="fc-three"><label>Resultado<select name="rating">${options(['1','2','3','4','5'],'3')}</select></label><label>Respuesta grupo<select name="response">${options(['Muy baja','Baja','Irregular','Buena','Muy buena'],'Buena')}</select></label><label>Siguiente decisión<select name="next">${options(['Repetir igual','Repetir con ajuste','Progresar','Cambiar tarea','Dar por consolidado'],'Repetir con ajuste')}</select></label></div><label>Qué funcionó<textarea name="worked"></textarea></label><label>Qué ajustar<textarea name="adjust"></textarea></label><button class="primary">Guardar diario</button></form></article><article class="panel"><h3>Historial de sesiones</h3><div id="fc-diary-list"></div></article></div></div><div class="fc-pane" data-pane="map"><article class="panel"><h3>Mapa de necesidades</h3><p class="fc-muted">Se calcula con los objetivos de planificación y diarios guardados; no inventa una puntuación si no hay datos.</p><div id="fc-needs-map"></div></article></div>`;
  bindSubnav(root); wirePlanning(); renderPlanning();
}
function wirePlanning(){
  $('#fc-plan-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.planning.push({id:uid(),level:f.get('level'),priority:f.get('priority'),problem:f.get('problem'),status:f.get('status'),rating:Number(f.get('rating')),start:f.get('start'),end:f.get('end'),note:f.get('note').trim()});saveState();renderPlanning();});
  $('#fc-diary-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.diary.push({id:uid(),date:f.get('date'),problem:f.get('problem'),rating:Number(f.get('rating')),response:f.get('response'),next:f.get('next'),worked:f.get('worked').trim(),adjust:f.get('adjust').trim()});saveState();renderPlanning();});
  $('#fc-planificacion').addEventListener('click',e=>{const b=e.target.closest('[data-delete-kind]');if(!b)return;state[b.dataset.deleteKind]=state[b.dataset.deleteKind].filter(x=>x.id!==b.dataset.id);saveState();renderPlanning();});
}
function renderPlanning(){
  const pl=$('#fc-plan-list');if(pl)pl.innerHTML=state.planning.length?state.planning.slice().reverse().map(x=>`<div class="fc-row"><div><strong>${esc(x.problem)}</strong><div class="fc-muted">${esc(x.level)} · ${esc(x.priority)} · ${esc(x.status)} · ${x.rating}/5</div><div class="fc-small">${esc(PROBLEMS[x.problem]?.principle||'')}</div></div><button type="button" class="danger" data-delete-kind="planning" data-id="${x.id}">×</button></div>`).join(''):'<div class="fc-empty">Sin objetivos de planificación.</div>';
  const dl=$('#fc-diary-list');if(dl)dl.innerHTML=state.diary.length?state.diary.slice().reverse().map(x=>`<div class="fc-row"><div><strong>${formatDate(x.date)} · ${esc(x.problem)}</strong><div class="fc-muted">${x.rating}/5 · ${esc(x.response)} · ${esc(x.next)}</div>${x.adjust?`<div class="fc-small">Ajuste: ${esc(x.adjust)}</div>`:''}</div><button type="button" class="danger" data-delete-kind="diary" data-id="${x.id}">×</button></div>`).join(''):'<div class="fc-empty">Sin diarios guardados.</div>';
  const nm=$('#fc-needs-map');if(nm){const data={};state.planning.forEach(x=>{data[x.problem]??=[];data[x.problem].push(x.rating)});state.diary.forEach(x=>{data[x.problem]??=[];data[x.problem].push(x.rating)});const rows=Object.entries(data).map(([p,arr])=>[p,arr.reduce((a,b)=>a+b,0)/arr.length]).sort((a,b)=>a[1]-b[1]);nm.innerHTML=rows.length?rows.map(([p,v])=>`<div class="fc-progress"><strong>${esc(p)}</strong><div class="fc-bar"><span style="width:${Math.round(v/5*100)}%"></span></div><small>${v.toFixed(1)}</small></div>`).join(''):'<div class="fc-empty">Guarda planificación o diarios para construir el mapa.</div>';}
}

function setupCombinations(){
  const root=createSection('fc-combinaciones','Combinaciones','Parejas, tríos y líneas sin conclusiones automáticas'); addNav('fc-combinaciones','Combinaciones');
  root.innerHTML=`<article class="panel"><div class="fc-filter-grid"><label>Tipo<select id="fc-combo-type">${options(['Pareja','Trío','Línea defensiva','Centrocampo','Ataque'])}</select></label><label>Jugador A<select id="fc-combo-a">${playerOptions()}</select></label><label>Jugador B<select id="fc-combo-b">${playerOptions('p01')}</select></label><label>Jugador C<select id="fc-combo-c"><option value="">— Opcional —</option>${playerOptions()}</select></label><label>Muestra mínima<select id="fc-combo-min">${options(['30','60','90','120','180'],'60')}</select></label></div><div class="fc-note info">Esta beta no inventa estadísticas de coincidencia. Cuando Partido en vivo tenga eventos suficientes, este módulo calculará minutos juntos, GF/GC y contexto. Mientras tanto sirve para registrar combinaciones a observar.</div><div class="fc-actions"><button id="fc-combo-save" type="button" class="primary">Añadir combinación a observar</button></div></article><article class="panel" style="margin-top:14px"><h3>Combinaciones en seguimiento</h3><div id="fc-combo-list"></div></article>`;
  state.combinations ||= []; $('#fc-combo-save').addEventListener('click',()=>{const ids=[$('#fc-combo-a').value,$('#fc-combo-b').value,$('#fc-combo-c').value].filter(Boolean);if(new Set(ids).size!==ids.length)return alert('Selecciona jugadores diferentes.');state.combinations.push({id:uid(),type:$('#fc-combo-type').value,players:ids,min:Number($('#fc-combo-min').value),createdAt:Date.now()});saveState();renderCombinations();});root.addEventListener('click',e=>{const b=e.target.closest('[data-combo-delete]');if(!b)return;state.combinations=state.combinations.filter(x=>x.id!==b.dataset.comboDelete);saveState();renderCombinations();});renderCombinations();
}
function renderCombinations(){const el=$('#fc-combo-list');if(!el)return;el.innerHTML=state.combinations?.length?state.combinations.slice().reverse().map(x=>`<div class="fc-row"><div><strong>${esc(x.type)} · ${x.players.map(playerName).map(esc).join(' + ')}</strong><div class="fc-muted">Esperar al menos ${x.min} min de muestra antes de interpretar.</div></div><button type="button" class="danger" data-combo-delete="${x.id}">×</button></div>`).join(''):'<div class="fc-empty">Sin combinaciones marcadas para seguimiento.</div>';}

function setupRivals(){
  const root=createSection('fc-rivales','Rivales','Memoria útil para el siguiente enfrentamiento'); addNav('fc-rivales','Rivales');
  root.innerHTML=`<div class="fc-two"><article class="panel"><h3>Nueva ficha de rival</h3><form id="fc-rival-form" class="fc-form"><label>Rival<input name="name" required list="fc-rival-known" placeholder="Nombre del equipo"><datalist id="fc-rival-known"><option value="Vecindario Alevín C"><option value="Gran Canaria Alevín C"></datalist></label><div class="fc-two"><label>Sistema<select name="system">${options([...SYSTEMS_F7,'Otro / desconocido'],'Otro / desconocido')}</select></label><label>Altura de presión<select name="press">${options(['No observada','Alta','Media','Baja','Variable'],'No observada')}</select></label></div><label>Salida rival<select name="build">${options(['No observada','Corta desde portero','Directa/larga','Mixta','Busca banda','Busca delantero referencia'],'No observada')}</select></label><label>Principal fortaleza<select name="strength">${options(['No observada','Salida de balón','Juego interior','Velocidad por bandas','Duelo individual','Balón directo','Segunda jugada','Presión','Finalización','ABP'],'No observada')}</select></label><label>Debilidad aparente<select name="weakness">${options(['No observada','Espalda de defensas','Salida bajo presión','Defensa de banda','Defensa del centro','Transición defensiva','Segunda jugada','ABP defensiva','Repliegue'],'No observada')}</select></label><label>Notas<textarea name="note" placeholder="Solo hechos observados y decisiones que nos funcionaron."></textarea></label><button class="primary">Guardar rival</button></form></article><article class="panel"><h3>Historial</h3><div id="fc-rival-list"></div></article></div>`;
  $('#fc-rival-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.rivals.push({id:uid(),name:f.get('name').trim(),system:f.get('system'),press:f.get('press'),build:f.get('build'),strength:f.get('strength'),weakness:f.get('weakness'),note:f.get('note').trim(),date:today()});saveState();renderRivals();});root.addEventListener('click',e=>{const b=e.target.closest('[data-rival-delete]');if(!b)return;state.rivals=state.rivals.filter(x=>x.id!==b.dataset.rivalDelete);saveState();renderRivals();});renderRivals();
}
function renderRivals(){const el=$('#fc-rival-list');if(!el)return;el.innerHTML=state.rivals.length?state.rivals.slice().reverse().map(r=>`<div class="fc-card" style="margin-bottom:9px"><div class="fc-title-line"><h4>${esc(r.name)}</h4><button type="button" class="danger" data-rival-delete="${r.id}">×</button></div><div><span class="fc-tag">${esc(r.system)}</span><span class="fc-tag neutral">Presión ${esc(r.press)}</span></div><p><strong>Fortaleza:</strong> ${esc(r.strength)}<br><strong>Debilidad:</strong> ${esc(r.weakness)}</p>${r.note?`<p class="fc-small">${esc(r.note)}</p>`:''}</div>`).join(''):'<div class="fc-empty">Aún no has creado fichas de rival.</div>';}

function setupReports(){
  const root=createSection('fc-informes','Informes','Resumen generado desde lo guardado en la beta'); addNav('fc-informes','Informes');
  root.innerHTML=`<article class="panel"><div class="fc-filter-grid"><label>Tipo<select id="fc-report-type">${options(['Jugador','Postpartido','Planificación'])}</select></label><label>Jugador<select id="fc-report-player">${playerOptions()}</select></label></div><div class="fc-actions"><button id="fc-report-build" type="button" class="primary">Generar vista previa</button><button id="fc-report-print" type="button" class="secondary">Imprimir / guardar PDF</button></div></article><div id="fc-report" class="fc-report" style="margin-top:14px"><div class="fc-empty">Selecciona un informe.</div></div>`;
  $('#fc-report-build').addEventListener('click',renderReport);$('#fc-report-print').addEventListener('click',()=>window.print());
}
function renderReport(){const type=$('#fc-report-type').value,root=$('#fc-report');if(type==='Jugador'){const id=$('#fc-report-player').value,p=playerById(id),objs=state.objectives.filter(x=>x.playerId===id),pos=state.positionTrials.filter(x=>x.playerId===id),ev=state.evaluations.filter(x=>x.playerId===id);root.innerHTML=`<h3>#${esc(p.number)} · ${esc(p.name)}</h3><p>${esc(p.positions.join(' · ')||'Sin posición definida')} · Pierna ${esc(p.foot)} · Última puntuación: ${p.rating??'—'}/5</p><h4>Objetivos</h4>${objs.length?objs.map(x=>`<p><strong>${esc(x.principle)}</strong> · ${esc(x.status)} · ${esc(x.priority)}</p>`).join(''):'<p class="fc-muted">Sin objetivos.</p>'}<h4>Pruebas de posición</h4>${pos.length?pos.map(x=>`<p>${formatDate(x.date)} · <strong>${esc(x.position)}</strong> · ${x.rating}/5 · ${esc(x.result)}</p>`).join(''):'<p class="fc-muted">Sin pruebas.</p>'}<h4>Evaluaciones</h4>${ev.length?ev.map(x=>`<p>${formatDate(x.date)} · ${esc(x.criterion)} · <strong>${x.rating}/5</strong></p>`).join(''):'<p class="fc-muted">Sin evaluaciones.</p>'}`;}else if(type==='Postpartido'){const x=state.postMatches.at(-1);root.innerHTML=x?`<h3>Último postpartido</h3><p><strong>Problemas:</strong> ${x.problems.map(esc).join(' · ')}</p><p><strong>Causa probable:</strong> ${esc(x.cause)}</p><p><strong>Evidencia:</strong> ${esc(x.evidence||'Sin nota')}</p><h4>Principios</h4>${x.problems.map(p=>`<p>${esc(PROBLEMS[p]?.principle||'')}</p>`).join('')}`:'<div class="fc-empty">No hay postpartidos guardados.</div>';}else{root.innerHTML=`<h3>Planificación</h3>${state.planning.length?state.planning.map(x=>`<p><strong>${esc(x.level)} · ${esc(x.problem)}</strong> · ${x.rating}/5 · ${esc(x.status)}</p>`).join(''):'<p class="fc-muted">Sin objetivos.</p>'}<h4>Últimos diarios</h4>${state.diary.slice(-5).reverse().map(x=>`<p>${formatDate(x.date)} · ${esc(x.problem)} · ${x.rating}/5 · ${esc(x.next)}</p>`).join('')||'<p class="fc-muted">Sin diarios.</p>'}`;}}

function setupIdentity(){
  const root=createSection('fc-identidad','Identidad del equipo','Escudo y colores propios sin cambiar la marca FútbolControl'); addNav('fc-identidad','Identidad');
  const i=state.identity; root.innerHTML=`<div class="fc-two"><article class="panel"><h3>Personalización</h3><form id="fc-identity-form" class="fc-form"><label>Nombre del equipo<input name="teamName" value="${esc(i.teamName)}"></label><label>Escudo del club<input name="crest" type="file" accept="image/*"></label><div class="fc-color-row"><label>Principal<input name="primary" type="color" value="${i.primary}"></label><label>Secundario<input name="secondary" type="color" value="${i.secondary}"></label><label>Acento<input name="accent" type="color" value="${i.accent}"></label></div><div class="fc-actions"><button class="primary">Aplicar</button><button id="fc-identity-reset" type="button" class="secondary">Restablecer</button></div></form></article><article class="panel"><h3>Vista previa</h3><div class="fc-identity-preview"><img id="fc-crest-preview" class="fc-crest" src="${i.crest||'lab/futbolcontrol-logo.svg'}" alt="Escudo"><div><strong id="fc-team-preview">${esc(i.teamName)}</strong><p class="fc-muted">El escudo identifica al equipo. FútbolControl sigue siendo la marca de la aplicación.</p></div></div></article></div>`;
  const form=$('#fc-identity-form');form.addEventListener('submit',e=>{e.preventDefault();const file=form.elements.crest.files[0];const commit=(crest)=>{state.identity={teamName:form.elements.teamName.value.trim()||'Mi equipo',primary:form.elements.primary.value,secondary:form.elements.secondary.value,accent:form.elements.accent.value,crest:crest??state.identity.crest};saveState();applyIdentity();$('#fc-team-preview').textContent=state.identity.teamName;$('#fc-crest-preview').src=state.identity.crest||'lab/futbolcontrol-logo.svg';};if(file){if(file.size>1_500_000)return alert('Para la beta usa un escudo de menos de 1,5 MB.');const r=new FileReader();r.onload=()=>commit(r.result);r.readAsDataURL(file);}else commit();});$('#fc-identity-reset').addEventListener('click',()=>{state.identity=defaultState().identity;saveState();location.reload();});
}

function setupAuditPanel(){
  const settings=$('#ajustes .settings-grid');if(!settings)return;const card=document.createElement('article');card.className='panel';card.innerHTML=`<h3>FútbolControl Beta · aislamiento</h3><p><strong>Base local:</strong> futbolcontrol-lab-v2</p><p><strong>Supabase:</strong> desactivado en esta copia.</p><p><strong>Plantilla inicial:</strong> ${PLAYERS.length} jugadores reales copiados solo como datos de prueba.</p><p class="meta">Borrar los datos del navegador o la rama beta elimina la prueba sin afectar CampoBase validado.</p>`;settings.prepend(card);
}

function init(){
  if(window.__futbolControlBetaLoaded)return;window.__futbolControlBetaLoaded=true;
  const link=document.createElement('link');link.rel='stylesheet';link.href='lab/beta-ui.css';document.head.appendChild(link);
  setupBrand(); setupDashboard(); setupDevelopment(); setupPostmatch(); setupPlanning(); setupCombinations(); setupRivals(); setupReports(); setupIdentity(); setupAuditPanel();
  // Abrir Inicio beta al arrancar la preview.
  $$('.view').forEach(v=>v.classList.toggle('active',v.id==='fc-inicio')); $$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='fc-inicio'));
}

setTimeout(init, 450);
